### PR TITLE
Add scripts for local servers

### PR DESCRIPTION
**Pull request by urakagi**
Add three scripts to set environment variables needed. Write down commands as script files.

### CODE REVIEW

**Comment by metasoarous** [comment]
Thanks for putting this together. A couple notes:

* Let's stick to the pattern in the rest of the repos of having a `.env_dev` file of environment variables that you source like `source .env_dev`. I actually don't like this pattern, and would like to move away from environment variables to config files for security concerns. But until we get there, let's stick with the existing pattern to avoid confusion.
* There's no `SERVER_PORT` environment variable.
* There's already a script for running the math worker in `bin/run`. Let's stick with this unless there's a good reason not to.
* I'm somewhat nonplus on your wrapper for the `export` comand as a shell script; This command has a bunch of options, which become hidden if we coax people to learn this wrapped version. I'd rather just add some content to the README about how you call various subcommands of `lein run`.

**Comment by urakagi** [comment]
Thank you @metasoarous,
1. I super hate the environment variable so move to config files is very good for me.
2. OK.
3. I just don't understand the parameters of the original `bin/run`, so I just write a new script. Also, the worker reboot can't detect `polisMath` error and will be unstoppable.
4. That will be a better solution, of course. After we moved to config files, this script can be erased.

**Comment by patcon** [comment]
ohai! is this PR still worth pulling anything out of, or should we close?

**Comment by patcon** [comment]
> This command has a bunch of options, which become hidden if we coax people to learn this wrapped version. I'd rather just add some content to the README about how you call various subcommands of lein run.

:-1: imho curious ppl who want to know about advanced flags know how to look into an executable :) simple binaries with defaults, and docs for the keeners. @urakagi's script looks exactly like what I'd expect, or alternatively hidden within a Makefile. cc @joshsmith2 (i think this is what you're looking for for data exports)

I'll submit another PR addressing your reco's as part of https://github.com/pol-is/polis-issues/issues/138, and close this one if that supercedes it

**Comment by patcon** [comment]
Closing this as part of repo transfer (https://github.com/pol-is/polis-issues/issues/134), but will cross-ref here so convo not lost: https://github.com/pol-is/polis-issues/issues/138

**Pull request closed without merging**
